# TestNG 异常| TestNG 教程

> 原文:# t0]https://www . software extingmaterial . com/test g-exception/

## 测试 g 异常:

在这篇文章中，我将展示如何使用 TestNG Exception(即， **expectedExceptions)** 参数和@Test 注释。TestNG 提供了跟踪代码异常处理的选项。

首先，我们看到一个没有使用 TestNG Exception 的基本程序。

创建了一个 java 类，比如说 TestNGException.java，并在方法 testException()中添加了一个错误条件。

Java

```java
package softwareTestingMaterial;
import org.testng.annotations.Test;
public class TestNGException {

	@Test
	public void testException() {
		System.out.println("SoftwareTestingMaterial.com");
		int i = 1 / 0;	
	}
}
```

**测试 g.xml:**

```java
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="softwaretestingmaterial">
	<test name="testngTest">
		<classes>
			<class name="softwareTestingMaterial.TestNGException" />
		</classes>
	</test>	
</suite>
```

**控制台输出:**

```java
[TestNG] Running:

SoftwareTestingMaterial.com

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

从测试结果可以看出，testException `()`方法在执行过程中被 TestNG 标记为失败。

现在让我们看看 TestNG 异常的运行情况。

如果你喜欢这个视频，那么请订阅我们的 YouTube 频道以获得更多的视频教程。

在使用@Test 注释时，使用***expected exceptions***属性值提到了运行以下测试时要验证的预期异常。

Java

```java
package softwareTestingMaterial;
import org.testng.annotations.Test;
public class TestNGException {

	@Test(expectedExceptions = ArithmeticException.class)
	public void testException() {
		System.out.println("SoftwareTestingMaterial.com");
		int i = 1 / 0;	
	}
}
```

**测试 g.xml:**

```java
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="softwaretestingmaterial">
	<test name="testngTest">
		<classes>
			<class name="softwareTestingMaterial.TestNGException" />
		</classes>
	</test>	
</suite>
```

**控制台输出:**

```java
[TestNG] Running:

SoftwareTestingMaterial.com

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

从测试结果可以看出，testException `()`方法在执行过程中被 TestNG 标记为通过。

你可以在这里找到完整的 TestNG 教程。

> [TestNG 完整教程](https://www.softwaretestingmaterial.com/testng-tutorial/)

如果你不是我博客的经常读者，那么我强烈推荐你使用下面的链接注册免费的电子邮件时事通讯。