exception_details/__init__.py,sha256=xY-LKniO90kRIwvWPnhy2ynpttvKZe621JFSyL6dxNM,286
exception_details/_version.py,sha256=Oe4RpQz3LWJXAuim9XB_9_sjdlb2xwZavpabqp46I9o,534
exception_details/exception_details.py,sha256=gfwNB2tftUiYZG4O7inn2xicJ0KX9XWrU36Nm9dWo7g,5474
exception_details-0.0.2.dist-info/LICENSE,sha256=9HsmUbkMFZDTY_7eyGX6_7F-jwhNF1PxA_6J37d5YPA,1095
exception_details-0.0.2.dist-info/METADATA,sha256=00RvgTzGZ0o6Sh19oZ1qqIgZ37O1zly6F7_5TfGqTjo,2471
exception_details-0.0.2.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
exception_details-0.0.2.dist-info/top_level.txt,sha256=oI-s3hCBa08Bax10Tt2Du6FiUdeo6FzFjHYv6bjEEpk,18
exception_details-0.0.2.dist-info/RECORD,,
