exception_details/__init__.py,sha256=1YYNOkx6rocfHyCX4SXBZQnLfFR59OKDQ7BXbe0HHeA,187
exception_details/_version.py,sha256=8829E1TWNLQzK4os9fHRzgCUXT4B0rDTd0YMGrsThFs,534
exception_details/exception_details.py,sha256=zKEkuv3f2kq6wuIFDZwdtdpKaM4WWw7vQVbpcxrnNHc,5392
exception_details-0.0.0.dist-info/LICENSE,sha256=9HsmUbkMFZDTY_7eyGX6_7F-jwhNF1PxA_6J37d5YPA,1095
exception_details-0.0.0.dist-info/METADATA,sha256=E2ArctreCtK3k-j5DHVhSvuJdf4R6L2hXt9uiSMP2G0,2471
exception_details-0.0.0.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
exception_details-0.0.0.dist-info/top_level.txt,sha256=oI-s3hCBa08Bax10Tt2Du6FiUdeo6FzFjHYv6bjEEpk,18
exception_details-0.0.0.dist-info/RECORD,,
